// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_window_info`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NEXT_LISTENER_ID`, `WINDOW_LISTENERS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `deref`, `fmt`, `initialize`, `initialize`

WindowDetails getActiveWindowInfo() =>
    RustLib.instance.api.crateApiActiveWindowListenerGetActiveWindowInfo();

List<WindowDetails> getOpenWindowsInfo() =>
    RustLib.instance.api.crateApiActiveWindowListenerGetOpenWindowsInfo();

String getWindowIconData({required int windowId}) => RustLib.instance.api
    .crateApiActiveWindowListenerGetWindowIconData(windowId: windowId);

bool isPlatformSupported() =>
    RustLib.instance.api.crateApiActiveWindowListenerIsPlatformSupported();

String getCurrentPlatform() =>
    RustLib.instance.api.crateApiActiveWindowListenerGetCurrentPlatform();

Stream<WindowDetails> startWindowListenerStream() =>
    RustLib.instance.api
        .crateApiActiveWindowListenerStartWindowListenerStream();

Stream<WindowDetails> startWindowListener() =>
    RustLib.instance.api.crateApiActiveWindowListenerStartWindowListener();

bool stopWindowListener({required BigInt listenerId}) => RustLib.instance.api
    .crateApiActiveWindowListenerStopWindowListener(listenerId: listenerId);

class WindowDetails {
  final int id;
  final String title;
  final (int, int, int, int) position;
  final bool isFullScreen;
  final String processName;
  final String processPath;
  final int processId;
  final String os;

  const WindowDetails({
    required this.id,
    required this.title,
    required this.position,
    required this.isFullScreen,
    required this.processName,
    required this.processPath,
    required this.processId,
    required this.os,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      position.hashCode ^
      isFullScreen.hashCode ^
      processName.hashCode ^
      processPath.hashCode ^
      processId.hashCode ^
      os.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowDetails &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          position == other.position &&
          isFullScreen == other.isFullScreen &&
          processName == other.processName &&
          processPath == other.processPath &&
          processId == other.processId &&
          os == other.os;
}
