// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fallback_send_notification`, `send_notification_linux`, `send`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NotificationBuilder`, `NotificationUrgency`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Sends a desktop notification with the specified title and message.
///
/// # Arguments
///
/// * `title` - The title of the notification
/// * `message` - The content/body of the notification
/// * `icon_path` - Optional path to an icon file (PNG, JPEG, etc.)
///
/// # Returns
///
/// A `Result` indicating success or failure
///
/// # Cross-platform Compatibility
///
/// - Windows: Uses PowerShell or Windows Toast Notifications
/// - macOS: Uses AppleScript or terminal-notifier
/// - Linux: Uses notify-send, kdialog, zenity, or xmessage
///
/// # Example
///
/// ```rust
/// use crate::api::desktop_notification::send_notification;
///
/// fn notify_user() -> Result<()> {
///     send_notification(
///         "Task Complete".to_string(),
///         "Your long-running task has finished successfully!".to_string(),
///         None
///     )
/// }
/// ```
Future<void> sendNotification({
  required String title,
  required String message,
  String? iconPath,
}) => RustLib.instance.api.crateApiDesktopNotificationSendNotification(
  title: title,
  message: message,
  iconPath: iconPath,
);

/// Adds the current module to the lib.rs file to make it accessible.
/// This function is purely for documentation and should not be called.
Future<void> registerModule() =>
    RustLib.instance.api.crateApiDesktopNotificationRegisterModule();

/// Advanced notification with additional options - FFI-friendly version
Future<void> sendNotificationWithOptions({
  required String title,
  required String message,
  String? iconPath,
  BigInt? timeoutSeconds,
  int? urgencyLevel,
}) =>
    RustLib.instance.api.crateApiDesktopNotificationSendNotificationWithOptions(
      title: title,
      message: message,
      iconPath: iconPath,
      timeoutSeconds: timeoutSeconds,
      urgencyLevel: urgencyLevel,
    );
