// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Returns a list of all running processes on the system
/// Works on macOS, Linux, and Windows
Future<List<ProcessInfo>> getAllProcesses() =>
    RustLib.instance.api.crateApiGetAllProcessListGetAllProcesses();

/// Provides platform-specific information about process access
Future<String> getProcessAccessInfo() =>
    RustLib.instance.api.crateApiGetAllProcessListGetProcessAccessInfo();

/// Returns a boolean indicating if the function can access process information
/// This can help diagnose permission issues
Future<bool> canAccessProcesses() =>
    RustLib.instance.api.crateApiGetAllProcessListCanAccessProcesses();

/// Finds a process by name (partial match)
Future<List<ProcessInfo>> findProcessByName({required String name}) =>
    RustLib.instance.api.crateApiGetAllProcessListFindProcessByName(name: name);

/// Kills a process by PID
/// Returns true if successful, false otherwise
Future<bool> killProcess({required int pid}) =>
    RustLib.instance.api.crateApiGetAllProcessListKillProcess(pid: pid);

/// Struct to represent process information
/// Compatible with Flutter Rust Bridge
class ProcessInfo {
  final int pid;
  final String name;
  final List<String> cmd;
  final BigInt memoryUsage;
  final double cpuUsage;

  const ProcessInfo({
    required this.pid,
    required this.name,
    required this.cmd,
    required this.memoryUsage,
    required this.cpuUsage,
  });

  @override
  int get hashCode =>
      pid.hashCode ^
      name.hashCode ^
      cmd.hashCode ^
      memoryUsage.hashCode ^
      cpuUsage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessInfo &&
          runtimeType == other.runtimeType &&
          pid == other.pid &&
          name == other.name &&
          cmd == other.cmd &&
          memoryUsage == other.memoryUsage &&
          cpuUsage == other.cpuUsage;
}
