// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Starts a polling-based keyboard listener that sends key events through the provided StreamSink.
/// It converts each Keycode into a lowercase String so we can track keys in a HashSet.
Stream<KeyboardEvent> startKeyboardListener() =>
    RustLib.instance.api.crateApiKeyboardListenerStartKeyboardListener();

class KeyboardEvent {
  final String key;
  final bool isKeyPress;

  const KeyboardEvent({required this.key, required this.isKeyPress});

  @override
  int get hashCode => key.hashCode ^ isKeyPress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyboardEvent &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          isKeyPress == other.isKeyPress;
}
