// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `mouse_button_to_event_data_from_str`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Starts a polling-based mouse listener that sends mouse events (button press/release with coordinates)
/// through the provided StreamSink.
Stream<MouseEvent> startMouseListener() =>
    RustLib.instance.api.crateApiMouseListenerStartMouseListener();

class MouseEvent {
  final String button;
  final bool isButtonPress;
  final (int, int) coords;
  final bool isLeftClick;
  final bool isRightClick;

  const MouseEvent({
    required this.button,
    required this.isButtonPress,
    required this.coords,
    required this.isLeftClick,
    required this.isRightClick,
  });

  @override
  int get hashCode =>
      button.hashCode ^
      isButtonPress.hashCode ^
      coords.hashCode ^
      isLeftClick.hashCode ^
      isRightClick.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MouseEvent &&
          runtimeType == other.runtimeType &&
          button == other.button &&
          isButtonPress == other.isButtonPress &&
          coords == other.coords &&
          isLeftClick == other.isLeftClick &&
          isRightClick == other.isRightClick;
}
