// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Takes a full screenshot of the primary monitor and returns it as a base64 encoded string.
///
/// # Returns
///
/// A `Result` containing the base64 encoded screenshot on success.
///
/// # Cross-platform Compatibility
///
/// - Windows: Works natively with multiple enterprise-grade fallback methods
/// - macOS: Works natively (requires permissions)
/// - Linux X11: Works natively
/// - Linux Wayland: Uses XWayland if available, or attempts fallback methods
///
/// # Windows Screenshot Methods (Professional Ordering - NirCmd Priority)
///
/// **Windows Primary Method:**
/// 1. **NirCmd** ⭐ PRIORITY #1 - Professional utility with bundled assets (completely silent)
/// 2. **Screenshots crate** - Cross-platform fallback method (fast and reliable)
///
/// **Windows Enterprise Fallback Chain:**
/// 3. **Memory-based** - Ultra-stealth, direct RAM→base64, Hubstaff-style (zero traces)
/// 4. **DirectShow** - Low-level Windows multimedia framework (enterprise-grade)
/// 5. **Win32 API** - Direct Windows GDI calls via PowerShell (maximum compatibility)
/// 6. **PowerShell** - Standard Windows scripting with System.Drawing (most compatible)
/// 7. **WMI** - Windows Management Instrumentation (enterprise monitoring)
/// 8. **FFmpeg** - Professional video/screen capture tool (if installed)
/// 9. **C# Inline** - Dynamic compilation and execution (reliable on .NET systems)
/// 10. **VBScript** - Windows Scripting Host (legacy fallback, last resort)
///
/// **Non-Windows Platforms:**
/// 1. **Screenshots crate** - Primary cross-platform method (fastest, most reliable)
/// 2. Platform-specific fallbacks
///
/// **NEW Ordering Rationale (NirCmd First):**
/// - **Maximum Stealth**: NirCmd provides completely silent operation with bundled assets
/// - **Zero Dependencies**: Bundled NirCmd requires no system installations
/// - **Enterprise Grade**: Professional tool designed for system administration
/// - **Universal Compatibility**: Works across all Windows versions (7, 8, 10, 11)
///
/// All methods are designed for:
/// - Complete silence (no visible windows, sounds, or notifications)
/// - No side effects (temporary files cleaned up immediately)
/// - Enterprise-grade reliability
/// - Cross-Windows version compatibility (7, 8, 10, 11)
Future<String> takeFullScreenshot() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTakeFullScreenshot();

Future<String> takeScreenshotWithScreenshotsCrate() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTakeScreenshotWithScreenshotsCrate();

Future<void> checkLinuxEnvironment() =>
    RustLib.instance.api.crateApiTakeFullScreenshotCheckLinuxEnvironment();

Future<String> takeScreenshotLinuxFallback() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTakeScreenshotLinuxFallback();

/// Test the primary screenshots crate method (cross-platform)
/// This is the fastest and most reliable method for all platforms
Future<String> testScreenshotsCrateMethod() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestScreenshotsCrateMethod();

/// Test Linux-specific fallback methods
Future<String> testLinuxFallbackMethods() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestLinuxFallbackMethods();

/// Test Linux environment checks
/// - Wayland/X11 detection
/// - XWayland availability
/// - Display server compatibility
Future<void> testLinuxEnvironmentCheck() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestLinuxEnvironmentCheck();

/// Run all available screenshot methods for current platform
/// Returns a comprehensive test report
Future<List<String>> testAllAvailableMethods() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestAllAvailableMethods();

Future<void> checkWindowsEnvironment() =>
    RustLib.instance.api.crateApiTakeFullScreenshotCheckWindowsEnvironment();

Future<String> extractBundledNircmd() =>
    RustLib.instance.api.crateApiTakeFullScreenshotExtractBundledNircmd();

Future<bool> isNircmdAvailable() =>
    RustLib.instance.api.crateApiTakeFullScreenshotIsNircmdAvailable();

Future<String> takeScreenshotWindowsCsharp() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTakeScreenshotWindowsCsharp();

Future<String> takeScreenshotWindowsDirectshow() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTakeScreenshotWindowsDirectshow();

Future<String> takeScreenshotWindowsFfmpeg() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTakeScreenshotWindowsFfmpeg();

Future<String> takeScreenshotWindowsMemory() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTakeScreenshotWindowsMemory();

Future<String> takeScreenshotWindowsNircmd() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTakeScreenshotWindowsNircmd();

Future<String> takeScreenshotWindowsPowershell() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTakeScreenshotWindowsPowershell();

Future<String> takeScreenshotWindowsVbscript() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTakeScreenshotWindowsVbscript();

Future<String> takeScreenshotWindowsWin32() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTakeScreenshotWindowsWin32();

Future<String> takeScreenshotWindowsWmi() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTakeScreenshotWindowsWmi();

Future<String> testBundledNircmdExtraction() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTestBundledNircmdExtraction();

Future<bool> testNircmdAvailability() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestNircmdAvailability();

Future<String> testNircmdCapabilities() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestNircmdCapabilities();

Future<String> testNircmdScreenshotSimple() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestNircmdScreenshotSimple();

Future<void> testWindowsEnvironmentCheck() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTestWindowsEnvironmentCheck();

Future<String> testWindowsMethod1Nircmd() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod1Nircmd();

Future<String> testWindowsMethod2Powershell() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTestWindowsMethod2Powershell();

Future<String> testWindowsMethod3Memory() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod3Memory();

Future<String> testWindowsMethod4Directshow() =>
    RustLib.instance.api
        .crateApiTakeFullScreenshotTestWindowsMethod4Directshow();

Future<String> testWindowsMethod5Win32() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod5Win32();

Future<String> testWindowsMethod6Wmi() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod6Wmi();

Future<String> testWindowsMethod7Ffmpeg() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod7Ffmpeg();

Future<String> testWindowsMethod8Csharp() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod8Csharp();

Future<String> testWindowsMethod9Vbscript() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod9Vbscript();
