// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/active_window_listener.dart';
import 'api/desktop_notification.dart';
import 'api/get_all_process_list.dart';
import 'api/keyboard_listener.dart';
import 'api/mouse_listener.dart';
import 'api/simple.dart';
import 'api/take_full_screenshot.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
    await api.crateApiTakeFullScreenshotInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1874832048;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_pi_task_watch',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiGetAllProcessListCanAccessProcesses();

  Future<void> crateApiTakeFullScreenshotCheckLinuxEnvironment();

  Future<void> crateApiTakeFullScreenshotCheckWindowsEnvironment();

  Future<String> crateApiTakeFullScreenshotExtractBundledNircmd();

  Future<List<ProcessInfo>> crateApiGetAllProcessListFindProcessByName({
    required String name,
  });

  WindowDetails crateApiActiveWindowListenerGetActiveWindowInfo();

  Future<List<ProcessInfo>> crateApiGetAllProcessListGetAllProcesses();

  String crateApiActiveWindowListenerGetCurrentPlatform();

  List<WindowDetails> crateApiActiveWindowListenerGetOpenWindowsInfo();

  Future<String> crateApiGetAllProcessListGetProcessAccessInfo();

  String crateApiActiveWindowListenerGetWindowIconData({required int windowId});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiTakeFullScreenshotInitApp();

  Future<bool> crateApiTakeFullScreenshotIsNircmdAvailable();

  bool crateApiActiveWindowListenerIsPlatformSupported();

  Future<bool> crateApiGetAllProcessListKillProcess({required int pid});

  Future<void> crateApiDesktopNotificationRegisterModule();

  Future<void> crateApiDesktopNotificationSendNotification({
    required String title,
    required String message,
    String? iconPath,
  });

  Future<void> crateApiDesktopNotificationSendNotificationWithOptions({
    required String title,
    required String message,
    String? iconPath,
    BigInt? timeoutSeconds,
    int? urgencyLevel,
  });

  Stream<KeyboardEvent> crateApiKeyboardListenerStartKeyboardListener();

  Stream<MouseEvent> crateApiMouseListenerStartMouseListener();

  Stream<WindowDetails> crateApiActiveWindowListenerStartWindowListener();

  Stream<WindowDetails> crateApiActiveWindowListenerStartWindowListenerStream();

  bool crateApiActiveWindowListenerStopWindowListener({
    required BigInt listenerId,
  });

  Future<String> crateApiTakeFullScreenshotTakeFullScreenshot();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotLinuxFallback();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsCsharp();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsDirectshow();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsFfmpeg();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsMemory();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsNircmd();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsPowershell();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsVbscript();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsWin32();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsWmi();

  Future<String> crateApiTakeFullScreenshotTakeScreenshotWithScreenshotsCrate();

  Future<List<String>> crateApiTakeFullScreenshotTestAllAvailableMethods();

  Future<String> crateApiTakeFullScreenshotTestBundledNircmdExtraction();

  Future<void> crateApiTakeFullScreenshotTestLinuxEnvironmentCheck();

  Future<String> crateApiTakeFullScreenshotTestLinuxFallbackMethods();

  Future<bool> crateApiTakeFullScreenshotTestNircmdAvailability();

  Future<String> crateApiTakeFullScreenshotTestNircmdCapabilities();

  Future<String> crateApiTakeFullScreenshotTestNircmdScreenshotSimple();

  Future<String> crateApiTakeFullScreenshotTestScreenshotsCrateMethod();

  Future<void> crateApiTakeFullScreenshotTestWindowsEnvironmentCheck();

  Future<String> crateApiTakeFullScreenshotTestWindowsMethod1Nircmd();

  Future<String> crateApiTakeFullScreenshotTestWindowsMethod2Powershell();

  Future<String> crateApiTakeFullScreenshotTestWindowsMethod3Memory();

  Future<String> crateApiTakeFullScreenshotTestWindowsMethod4Directshow();

  Future<String> crateApiTakeFullScreenshotTestWindowsMethod5Win32();

  Future<String> crateApiTakeFullScreenshotTestWindowsMethod6Wmi();

  Future<String> crateApiTakeFullScreenshotTestWindowsMethod7Ffmpeg();

  Future<String> crateApiTakeFullScreenshotTestWindowsMethod8Csharp();

  Future<String> crateApiTakeFullScreenshotTestWindowsMethod9Vbscript();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiGetAllProcessListCanAccessProcesses() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetAllProcessListCanAccessProcessesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllProcessListCanAccessProcessesConstMeta =>
      const TaskConstMeta(debugName: "can_access_processes", argNames: []);

  @override
  Future<void> crateApiTakeFullScreenshotCheckLinuxEnvironment() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotCheckLinuxEnvironmentConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTakeFullScreenshotCheckLinuxEnvironmentConstMeta =>
      const TaskConstMeta(debugName: "check_linux_environment", argNames: []);

  @override
  Future<void> crateApiTakeFullScreenshotCheckWindowsEnvironment() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotCheckWindowsEnvironmentConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotCheckWindowsEnvironmentConstMeta =>
      const TaskConstMeta(debugName: "check_windows_environment", argNames: []);

  @override
  Future<String> crateApiTakeFullScreenshotExtractBundledNircmd() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotExtractBundledNircmdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTakeFullScreenshotExtractBundledNircmdConstMeta =>
      const TaskConstMeta(debugName: "extract_bundled_nircmd", argNames: []);

  @override
  Future<List<ProcessInfo>> crateApiGetAllProcessListFindProcessByName({
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_process_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetAllProcessListFindProcessByNameConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllProcessListFindProcessByNameConstMeta =>
      const TaskConstMeta(
        debugName: "find_process_by_name",
        argNames: ["name"],
      );

  @override
  WindowDetails crateApiActiveWindowListenerGetActiveWindowInfo() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_window_details,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiActiveWindowListenerGetActiveWindowInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiActiveWindowListenerGetActiveWindowInfoConstMeta =>
      const TaskConstMeta(debugName: "get_active_window_info", argNames: []);

  @override
  Future<List<ProcessInfo>> crateApiGetAllProcessListGetAllProcesses() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_process_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetAllProcessListGetAllProcessesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllProcessListGetAllProcessesConstMeta =>
      const TaskConstMeta(debugName: "get_all_processes", argNames: []);

  @override
  String crateApiActiveWindowListenerGetCurrentPlatform() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiActiveWindowListenerGetCurrentPlatformConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiActiveWindowListenerGetCurrentPlatformConstMeta =>
      const TaskConstMeta(debugName: "get_current_platform", argNames: []);

  @override
  List<WindowDetails> crateApiActiveWindowListenerGetOpenWindowsInfo() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_window_details,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiActiveWindowListenerGetOpenWindowsInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiActiveWindowListenerGetOpenWindowsInfoConstMeta =>
      const TaskConstMeta(debugName: "get_open_windows_info", argNames: []);

  @override
  Future<String> crateApiGetAllProcessListGetProcessAccessInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetAllProcessListGetProcessAccessInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllProcessListGetProcessAccessInfoConstMeta =>
      const TaskConstMeta(debugName: "get_process_access_info", argNames: []);

  @override
  String crateApiActiveWindowListenerGetWindowIconData({
    required int windowId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(windowId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiActiveWindowListenerGetWindowIconDataConstMeta,
        argValues: [windowId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiActiveWindowListenerGetWindowIconDataConstMeta =>
      const TaskConstMeta(
        debugName: "get_window_icon_data",
        argNames: ["windowId"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiTakeFullScreenshotInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTakeFullScreenshotInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTakeFullScreenshotInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiTakeFullScreenshotIsNircmdAvailable() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTakeFullScreenshotIsNircmdAvailableConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTakeFullScreenshotIsNircmdAvailableConstMeta =>
      const TaskConstMeta(debugName: "is_nircmd_available", argNames: []);

  @override
  bool crateApiActiveWindowListenerIsPlatformSupported() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiActiveWindowListenerIsPlatformSupportedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiActiveWindowListenerIsPlatformSupportedConstMeta =>
      const TaskConstMeta(debugName: "is_platform_supported", argNames: []);

  @override
  Future<bool> crateApiGetAllProcessListKillProcess({required int pid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(pid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetAllProcessListKillProcessConstMeta,
        argValues: [pid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllProcessListKillProcessConstMeta =>
      const TaskConstMeta(debugName: "kill_process", argNames: ["pid"]);

  @override
  Future<void> crateApiDesktopNotificationRegisterModule() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDesktopNotificationRegisterModuleConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopNotificationRegisterModuleConstMeta =>
      const TaskConstMeta(debugName: "register_module", argNames: []);

  @override
  Future<void> crateApiDesktopNotificationSendNotification({
    required String title,
    required String message,
    String? iconPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_String(message, serializer);
          sse_encode_opt_String(iconPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopNotificationSendNotificationConstMeta,
        argValues: [title, message, iconPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopNotificationSendNotificationConstMeta =>
      const TaskConstMeta(
        debugName: "send_notification",
        argNames: ["title", "message", "iconPath"],
      );

  @override
  Future<void> crateApiDesktopNotificationSendNotificationWithOptions({
    required String title,
    required String message,
    String? iconPath,
    BigInt? timeoutSeconds,
    int? urgencyLevel,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_String(message, serializer);
          sse_encode_opt_String(iconPath, serializer);
          sse_encode_opt_box_autoadd_u_64(timeoutSeconds, serializer);
          sse_encode_opt_box_autoadd_i_32(urgencyLevel, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiDesktopNotificationSendNotificationWithOptionsConstMeta,
        argValues: [title, message, iconPath, timeoutSeconds, urgencyLevel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDesktopNotificationSendNotificationWithOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "send_notification_with_options",
        argNames: [
          "title",
          "message",
          "iconPath",
          "timeoutSeconds",
          "urgencyLevel",
        ],
      );

  @override
  Stream<KeyboardEvent> crateApiKeyboardListenerStartKeyboardListener() {
    final sink = RustStreamSink<KeyboardEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_keyboard_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 21,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiKeyboardListenerStartKeyboardListenerConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiKeyboardListenerStartKeyboardListenerConstMeta =>
      const TaskConstMeta(
        debugName: "start_keyboard_listener",
        argNames: ["sink"],
      );

  @override
  Stream<MouseEvent> crateApiMouseListenerStartMouseListener() {
    final sink = RustStreamSink<MouseEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_mouse_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 22,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiMouseListenerStartMouseListenerConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMouseListenerStartMouseListenerConstMeta =>
      const TaskConstMeta(
        debugName: "start_mouse_listener",
        argNames: ["sink"],
      );

  @override
  Stream<WindowDetails> crateApiActiveWindowListenerStartWindowListener() {
    final sink = RustStreamSink<WindowDetails>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_window_details_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiActiveWindowListenerStartWindowListenerConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiActiveWindowListenerStartWindowListenerConstMeta =>
      const TaskConstMeta(
        debugName: "start_window_listener",
        argNames: ["sink"],
      );

  @override
  Stream<WindowDetails>
  crateApiActiveWindowListenerStartWindowListenerStream() {
    final sink = RustStreamSink<WindowDetails>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_window_details_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiActiveWindowListenerStartWindowListenerStreamConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiActiveWindowListenerStartWindowListenerStreamConstMeta =>
      const TaskConstMeta(
        debugName: "start_window_listener_stream",
        argNames: ["sink"],
      );

  @override
  bool crateApiActiveWindowListenerStopWindowListener({
    required BigInt listenerId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(listenerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiActiveWindowListenerStopWindowListenerConstMeta,
        argValues: [listenerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiActiveWindowListenerStopWindowListenerConstMeta =>
      const TaskConstMeta(
        debugName: "stop_window_listener",
        argNames: ["listenerId"],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTakeFullScreenshot() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTakeFullScreenshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTakeFullScreenshotTakeFullScreenshotConstMeta =>
      const TaskConstMeta(debugName: "take_full_screenshot", argNames: []);

  @override
  Future<String> crateApiTakeFullScreenshotTakeScreenshotLinuxFallback() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTakeScreenshotLinuxFallbackConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotLinuxFallbackConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_linux_fallback",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsCsharp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTakeScreenshotWindowsCsharpConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotWindowsCsharpConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_windows_csharp",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsDirectshow() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTakeScreenshotWindowsDirectshowConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotWindowsDirectshowConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_windows_directshow",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsFfmpeg() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTakeScreenshotWindowsFfmpegConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotWindowsFfmpegConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_windows_ffmpeg",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsMemory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTakeScreenshotWindowsMemoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotWindowsMemoryConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_windows_memory",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsNircmd() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTakeScreenshotWindowsNircmdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotWindowsNircmdConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_windows_nircmd",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsPowershell() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTakeScreenshotWindowsPowershellConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotWindowsPowershellConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_windows_powershell",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsVbscript() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTakeScreenshotWindowsVbscriptConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotWindowsVbscriptConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_windows_vbscript",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsWin32() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTakeScreenshotWindowsWin32ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotWindowsWin32ConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_windows_win32",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTakeScreenshotWindowsWmi() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTakeScreenshotWindowsWmiConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotWindowsWmiConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_windows_wmi",
        argNames: [],
      );

  @override
  Future<String>
  crateApiTakeFullScreenshotTakeScreenshotWithScreenshotsCrate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTakeScreenshotWithScreenshotsCrateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTakeScreenshotWithScreenshotsCrateConstMeta =>
      const TaskConstMeta(
        debugName: "take_screenshot_with_screenshots_crate",
        argNames: [],
      );

  @override
  Future<List<String>> crateApiTakeFullScreenshotTestAllAvailableMethods() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTestAllAvailableMethodsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestAllAvailableMethodsConstMeta =>
      const TaskConstMeta(
        debugName: "test_all_available_methods",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestBundledNircmdExtraction() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTestBundledNircmdExtractionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestBundledNircmdExtractionConstMeta =>
      const TaskConstMeta(
        debugName: "test_bundled_nircmd_extraction",
        argNames: [],
      );

  @override
  Future<void> crateApiTakeFullScreenshotTestLinuxEnvironmentCheck() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTestLinuxEnvironmentCheckConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestLinuxEnvironmentCheckConstMeta =>
      const TaskConstMeta(
        debugName: "test_linux_environment_check",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestLinuxFallbackMethods() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTestLinuxFallbackMethodsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestLinuxFallbackMethodsConstMeta =>
      const TaskConstMeta(
        debugName: "test_linux_fallback_methods",
        argNames: [],
      );

  @override
  Future<bool> crateApiTakeFullScreenshotTestNircmdAvailability() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTakeFullScreenshotTestNircmdAvailabilityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestNircmdAvailabilityConstMeta =>
      const TaskConstMeta(debugName: "test_nircmd_availability", argNames: []);

  @override
  Future<String> crateApiTakeFullScreenshotTestNircmdCapabilities() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTestNircmdCapabilitiesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestNircmdCapabilitiesConstMeta =>
      const TaskConstMeta(debugName: "test_nircmd_capabilities", argNames: []);

  @override
  Future<String> crateApiTakeFullScreenshotTestNircmdScreenshotSimple() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTestNircmdScreenshotSimpleConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestNircmdScreenshotSimpleConstMeta =>
      const TaskConstMeta(
        debugName: "test_nircmd_screenshot_simple",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestScreenshotsCrateMethod() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTestScreenshotsCrateMethodConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestScreenshotsCrateMethodConstMeta =>
      const TaskConstMeta(
        debugName: "test_screenshots_crate_method",
        argNames: [],
      );

  @override
  Future<void> crateApiTakeFullScreenshotTestWindowsEnvironmentCheck() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTestWindowsEnvironmentCheckConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestWindowsEnvironmentCheckConstMeta =>
      const TaskConstMeta(
        debugName: "test_windows_environment_check",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestWindowsMethod1Nircmd() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 47,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTestWindowsMethod1NircmdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestWindowsMethod1NircmdConstMeta =>
      const TaskConstMeta(
        debugName: "test_windows_method_1_nircmd",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestWindowsMethod2Powershell() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 48,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTestWindowsMethod2PowershellConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestWindowsMethod2PowershellConstMeta =>
      const TaskConstMeta(
        debugName: "test_windows_method_2_powershell",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestWindowsMethod3Memory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTestWindowsMethod3MemoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestWindowsMethod3MemoryConstMeta =>
      const TaskConstMeta(
        debugName: "test_windows_method_3_memory",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestWindowsMethod4Directshow() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTestWindowsMethod4DirectshowConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestWindowsMethod4DirectshowConstMeta =>
      const TaskConstMeta(
        debugName: "test_windows_method_4_directshow",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestWindowsMethod5Win32() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTestWindowsMethod5Win32ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestWindowsMethod5Win32ConstMeta =>
      const TaskConstMeta(
        debugName: "test_windows_method_5_win32",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestWindowsMethod6Wmi() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 52,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTestWindowsMethod6WmiConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTakeFullScreenshotTestWindowsMethod6WmiConstMeta =>
      const TaskConstMeta(debugName: "test_windows_method_6_wmi", argNames: []);

  @override
  Future<String> crateApiTakeFullScreenshotTestWindowsMethod7Ffmpeg() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 53,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTestWindowsMethod7FfmpegConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestWindowsMethod7FfmpegConstMeta =>
      const TaskConstMeta(
        debugName: "test_windows_method_7_ffmpeg",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestWindowsMethod8Csharp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 54,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTakeFullScreenshotTestWindowsMethod8CsharpConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestWindowsMethod8CsharpConstMeta =>
      const TaskConstMeta(
        debugName: "test_windows_method_8_csharp",
        argNames: [],
      );

  @override
  Future<String> crateApiTakeFullScreenshotTestWindowsMethod9Vbscript() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 55,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateApiTakeFullScreenshotTestWindowsMethod9VbscriptConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTakeFullScreenshotTestWindowsMethod9VbscriptConstMeta =>
      const TaskConstMeta(
        debugName: "test_windows_method_9_vbscript",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<KeyboardEvent> dco_decode_StreamSink_keyboard_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MouseEvent> dco_decode_StreamSink_mouse_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<WindowDetails> dco_decode_StreamSink_window_details_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  KeyboardEvent dco_decode_keyboard_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeyboardEvent(
      key: dco_decode_String(arr[0]),
      isKeyPress: dco_decode_bool(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProcessInfo> dco_decode_list_process_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_process_info).toList();
  }

  @protected
  List<WindowDetails> dco_decode_list_window_details(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_window_details).toList();
  }

  @protected
  MouseEvent dco_decode_mouse_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MouseEvent(
      button: dco_decode_String(arr[0]),
      isButtonPress: dco_decode_bool(arr[1]),
      coords: dco_decode_record_i_32_i_32(arr[2]),
      isLeftClick: dco_decode_bool(arr[3]),
      isRightClick: dco_decode_bool(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  ProcessInfo dco_decode_process_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProcessInfo(
      pid: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      cmd: dco_decode_list_String(arr[2]),
      memoryUsage: dco_decode_u_64(arr[3]),
      cpuUsage: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  (int, int) dco_decode_record_i_32_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_i_32(arr[0]), dco_decode_i_32(arr[1]));
  }

  @protected
  (int, int, int, int) dco_decode_record_i_32_i_32_i_32_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) {
      throw Exception('Expected 4 elements, got ${arr.length}');
    }
    return (
      dco_decode_i_32(arr[0]),
      dco_decode_i_32(arr[1]),
      dco_decode_i_32(arr[2]),
      dco_decode_i_32(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WindowDetails dco_decode_window_details(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return WindowDetails(
      id: dco_decode_u_32(arr[0]),
      title: dco_decode_String(arr[1]),
      position: dco_decode_record_i_32_i_32_i_32_i_32(arr[2]),
      isFullScreen: dco_decode_bool(arr[3]),
      processName: dco_decode_String(arr[4]),
      processPath: dco_decode_String(arr[5]),
      processId: dco_decode_u_32(arr[6]),
      os: dco_decode_String(arr[7]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<KeyboardEvent> sse_decode_StreamSink_keyboard_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MouseEvent> sse_decode_StreamSink_mouse_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<WindowDetails> sse_decode_StreamSink_window_details_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  KeyboardEvent sse_decode_keyboard_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_isKeyPress = sse_decode_bool(deserializer);
    return KeyboardEvent(key: var_key, isKeyPress: var_isKeyPress);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProcessInfo> sse_decode_list_process_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProcessInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_process_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<WindowDetails> sse_decode_list_window_details(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WindowDetails>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_window_details(deserializer));
    }
    return ans_;
  }

  @protected
  MouseEvent sse_decode_mouse_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_button = sse_decode_String(deserializer);
    var var_isButtonPress = sse_decode_bool(deserializer);
    var var_coords = sse_decode_record_i_32_i_32(deserializer);
    var var_isLeftClick = sse_decode_bool(deserializer);
    var var_isRightClick = sse_decode_bool(deserializer);
    return MouseEvent(
      button: var_button,
      isButtonPress: var_isButtonPress,
      coords: var_coords,
      isLeftClick: var_isLeftClick,
      isRightClick: var_isRightClick,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProcessInfo sse_decode_process_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pid = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_cmd = sse_decode_list_String(deserializer);
    var var_memoryUsage = sse_decode_u_64(deserializer);
    var var_cpuUsage = sse_decode_f_32(deserializer);
    return ProcessInfo(
      pid: var_pid,
      name: var_name,
      cmd: var_cmd,
      memoryUsage: var_memoryUsage,
      cpuUsage: var_cpuUsage,
    );
  }

  @protected
  (int, int) sse_decode_record_i_32_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_i_32(deserializer);
    var var_field1 = sse_decode_i_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (int, int, int, int) sse_decode_record_i_32_i_32_i_32_i_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_i_32(deserializer);
    var var_field1 = sse_decode_i_32(deserializer);
    var var_field2 = sse_decode_i_32(deserializer);
    var var_field3 = sse_decode_i_32(deserializer);
    return (var_field0, var_field1, var_field2, var_field3);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WindowDetails sse_decode_window_details(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_position = sse_decode_record_i_32_i_32_i_32_i_32(deserializer);
    var var_isFullScreen = sse_decode_bool(deserializer);
    var var_processName = sse_decode_String(deserializer);
    var var_processPath = sse_decode_String(deserializer);
    var var_processId = sse_decode_u_32(deserializer);
    var var_os = sse_decode_String(deserializer);
    return WindowDetails(
      id: var_id,
      title: var_title,
      position: var_position,
      isFullScreen: var_isFullScreen,
      processName: var_processName,
      processPath: var_processPath,
      processId: var_processId,
      os: var_os,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_keyboard_event_Sse(
    RustStreamSink<KeyboardEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_keyboard_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_mouse_event_Sse(
    RustStreamSink<MouseEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_mouse_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_window_details_Sse(
    RustStreamSink<WindowDetails> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_window_details,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_keyboard_event(KeyboardEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_bool(self.isKeyPress, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_process_info(
    List<ProcessInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_process_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_window_details(
    List<WindowDetails> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_window_details(item, serializer);
    }
  }

  @protected
  void sse_encode_mouse_event(MouseEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.button, serializer);
    sse_encode_bool(self.isButtonPress, serializer);
    sse_encode_record_i_32_i_32(self.coords, serializer);
    sse_encode_bool(self.isLeftClick, serializer);
    sse_encode_bool(self.isRightClick, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_process_info(ProcessInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.pid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_String(self.cmd, serializer);
    sse_encode_u_64(self.memoryUsage, serializer);
    sse_encode_f_32(self.cpuUsage, serializer);
  }

  @protected
  void sse_encode_record_i_32_i_32((int, int) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.$1, serializer);
    sse_encode_i_32(self.$2, serializer);
  }

  @protected
  void sse_encode_record_i_32_i_32_i_32_i_32(
    (int, int, int, int) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.$1, serializer);
    sse_encode_i_32(self.$2, serializer);
    sse_encode_i_32(self.$3, serializer);
    sse_encode_i_32(self.$4, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_window_details(WindowDetails self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_record_i_32_i_32_i_32_i_32(self.position, serializer);
    sse_encode_bool(self.isFullScreen, serializer);
    sse_encode_String(self.processName, serializer);
    sse_encode_String(self.processPath, serializer);
    sse_encode_u_32(self.processId, serializer);
    sse_encode_String(self.os, serializer);
  }
}
